### PR TITLE
Removed duplicate definition

### PR DESCRIPTION
**Pull request by kaarthiksundar**
Function ``^(x::Interval{Float64}, r::Rational) = x^(convert(Interval{Float64}, r))`` already defined in IntervalArithmetic.jl

### CODE REVIEW

**Comment by kaarthiksundar** [comment]
@dpsanders I am using both IntervalArithmetic and Contractors in Alpine.jl's MOI interface and I am running into duplicate definitions. Let me know if there is something I can do to get the tests passed on the current branch.

**Comment by dpsanders** [comment]
What is the actual error that you are getting?

I'm interested what you are using in Alpine.jl?

**Comment by kaarthiksundar** [comment]
It is not an error, just a warning stating that the method definition is overwritten by intervalcontractors. I shall send you the actual warning in some time. I am using both interval arithmetic and contractors for doing bound propagation. Check https://github.com/lanl-ansi/Alpine.jl/blob/moi-wrapper/src/fbbt.jl

**Comment by kaarthiksundar** [comment]
I am basically constructing a DAG of all the nonlinear terms in the optimization problem and using it to propagate bounds to variables and constraints. I also can use it for some convexity detection which I have not implemented yet.

**Comment by dpsanders** [comment]
I don't get this warning. However, I think we should add this definition directly to IntervalArithmetic.jl.

**Comment by dpsanders** [comment]
That application is very interesting. Is there a way that can be factored out?

**Comment by kaarthiksundar** [comment]
> I don't get this warning. However, I think we should add this definition directly to IntervalArithmetic.jl.

Okay, it is a mistake on my end. I had a script which was importing the package twice. Sorry for the trouble. 

As far as the DAG construction and using Interval Arithmetic goes, yes, it can be factored out. Let me know which part you want factored out.

**Comment by kaarthiksundar** [comment]
@dpsanders The issue still shows up. The actual error is 
````WARNING: Method definition ^(IntervalArithmetic.Interval{Float64}, Base.Rational{T} where T<:Integer) in module IntervalArithmetic at /home/travis/.julia/packages/IntervalArithmetic/9q80F/src/intervals/functions.jl:10 overwritten in module IntervalContractors at /home/travis/.julia/packages/IntervalContractors/EI2Tp/src/arithmetic.jl:4.````

It shows up in the Travis Job log https://travis-ci.org/lanl-ansi/Alpine.jl/jobs/515953360

**Comment by kaarthiksundar** [comment]
@dpsanders Any update on this warning message?

**Comment by dpsanders** [comment]
I am still unable to reproduce this, but let's try removing this definition.

**Comment by dpsanders** [comment]
Tests are failing for an apparently unrelated reason. Did you try rebasing to master?

**Comment by kaarthiksundar** [comment]
Yes, I tried rebasing. I think there is an issue with the atan test in ``inv_trig.jl:33`` 

````julia
julia> atan_rev(Interval(-Inf, 0.0), entireinterval(Float64))[2]
[-1.63313e+16, 0]
````

But the test checks against ``Interval(-Inf, Inf)``. Is this correct? 

If I remove this definition, the warning in Alpine goes away.

**Comment by dpsanders** [comment]
I don't know what's going on with that `atan` example. Let's just change the test. It should surely give a result that has maximum value 0.

And let's remove the x^(rational) from here and move it to IntervalArithmetic.jl.

**Comment by kaarthiksundar** [comment]
@dpsanders Great, let me know how I can help.

**Comment by kaarthiksundar** [comment]
@dpsanders Let me know what I can do here. I am waiting on this PR for an upstream dependency. Also, I volunteer to move this package to the new package management system. Let me know how you want to proceed with this.

**Comment by dpsanders** [comment]
Sorry for the delay. If you could fix the failing test and update to Project.toml, let's just merge this!

**Comment by dpsanders** [comment]
Does #29 fix the failing test for you @kaarthiksundar?

**Comment by dpsanders** [comment]
I guess that should really be a separate PR

**Comment by dpsanders** [comment]
Sorry for the delay here.

I have merged #30 which fixes the atan test. You can rebase this PR against master or we can use #32 if that's easier.

**Comment by kaarthiksundar** [comment]
@dpsanders Finally, I have the bandwidth for this week. Closing this PR and sending you a new one. I merged https://github.com/JuliaIntervals/IntervalContractors.jl/pull/30 and posted the new PR.

**Pull request closed without merging**
