### PR TITLE
Removed duplicate definition

### PR DESCRIPTION
**Pull request by kaarthiksundar**

### CODE REVIEW

**Comment by dpsanders** [comment]
Could you please rebase against master instead of merging:

```
git rebase master
```

Thanks!

**Comment by kaarthiksundar** [comment]
Can you give me write access to the repo. This will be a lot easier.

**Comment by kaarthiksundar** [comment]
Forget it. Done, see new PR.

**Comment by dpsanders** [comment]
You don't need to make new prs, you can just force push to the same one.

**Comment by kaarthiksundar** [comment]
Oh, sorry, I did not know that can be done.

**Pull request closed without merging**
